<template>
  <q-btn
    color="info"
    icon="visibility"
    size="md"
    flat
    round
    dense
    @click="open_branch_status_dialog"
  >
    <q-tooltip class="bg-info" :delay="200">View</q-tooltip>
  </q-btn>
  <q-dialog v-model="brancheStatusDialog" full-width>
    <!-- style="width: 1000px; max-width: 90vw;" -->
    <!-- {{ props.branch }} -->
    <q-card class="my-card">
      <q-card-section
        class="row justify-between"
        style="background-color: #ef4444"
      >
        <div class="text-h6 text-white">
          <q-icon name="fa-solid fa-store" />
          {{ props.branch.name }}
        </div>
        <div class="text-white">
          <q-btn flat round dense icon="close" v-close-popup />
        </div>
      </q-card-section>
      <q-card-section>
        <q-table
          :rows="branchRawMaterialsRows"
          :columns="rawMaterialsColumns"
          class="table-container sticky-header"
          flat
          dense
          virtual-scroll
          v-model:pagination="pagination"
          :rows-per-page-options="[0]"
          hide-bottom
          style="height: 340px"
        >
          <template v-slot:body-cell-total_quantity="props">
            <q-td :props="props">
              <q-badge
                square
                class="text-white cursor-pointer"
                :class="getRawMaterialBadgeColor(props.row)"
              >
                {{ formatTotalQuantity(props.row) }}
                <q-tooltip class="bg-blue-grey-8" :offset="[10, 10]">
                  <div class="text-white">Edit Available Stocks</div>
                </q-tooltip>
              </q-badge>
            </q-td>
          </template>
        </q-table>
      </q-card-section>
    </q-card>
  </q-dialog>
</template>
<script setup>
import { computed, onMounted, ref } from "vue";
import { useWarehouseRawMaterialsStore } from "src/stores/warehouse-rawMaterials";

const warehouseRawMaterialsStore = useWarehouseRawMaterialsStore();
const branchRawMaterialsRows = computed(
  () => warehouseRawMaterialsStore.branchRawMaterials
);
const props = defineProps({
  branch: Object,
});
const pagination = ref({
  rowsPerPage: 0,
});
console.log("branch", props.branch);
const branchId = props.branch.id;

const reloadBranchRawMaterials = async (branchId) => {
  const response = await warehouseRawMaterialsStore.fetchBranchRawMaterials(
    branchId
  );
  console.log("response.value", response);
  branchRawMaterialsRows.value = response;
  console.log("branchRawMaterialsRowssss", branchRawMaterialsRows.value);
};

const brancheStatusDialog = ref();

const open_branch_status_dialog = () => {
  reloadBranchRawMaterials(branchId);
  brancheStatusDialog.value = true;
};

const getRawMaterialBadgeColor = (row) => {
  const totalQuantity = row.total_quantity;
  const unit = row.ingredients.unit;
  if (unit === "Grams" && totalQuantity < 1000) {
    return "bg-red";
  }

  let stockValue;
  if (totalQuantity >= 1000) {
    stockValue = totalQuantity / 1000;
  } else {
    stockValue = totalQuantity;
  }

  if (stockValue < 5) {
    if (stockValue <= 2) {
      return "bg-red";
    } else if (stockValue <= 3) {
      return "bg-warning";
    } else {
      return "bg-warning";
    }
  } else {
    return "bg-positive";
  }
};

const formatTotalQuantity = (row) => {
  const totalQuantity = row.total_quantity;
  const unit = row.ingredients.unit;

  if (totalQuantity > 1000) {
    const totalQuantityKilo = (totalQuantity / 1000).toFixed(2);
    if (totalQuantityKilo.endsWith(".00")) {
      return `${Math.round(totalQuantity / 1000)} kilos`;
    } else {
      return `${totalQuantityKilo} kilos`;
    }
  } else if (totalQuantity > 1) {
    return `${totalQuantity} ${unit}`;
  } else {
    return `${totalQuantity} ${unit}`;
  }
};

const rawMaterialsColumns = [
  {
    name: "name",
    required: true,
    label: "Name",
    align: "left",
    field: (row) => row.ingredients.name,
    format: (val) => `${val}`,
  },
  {
    name: "total_quantity",
    required: true,
    label: "Available Stocks",
    align: "left",
    field: (row) => row.total_quantity,
    format: (val) => `${val}`,
  },
];
</script>

<style scoped>
.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 20px;
}

.card {
  max-width: 100%;
}
.table-container {
  max-height: 400px; /* Adjust as needed */
  overflow: hidden;
}

.q-table-container {
  overflow: hidden !important; /* Target the container generated by q-table */
}
</style>
